name: sentry
on: pull_request

jobs:
    snuba:
      runs-on: ubuntu-16.04
      steps:
        # Checkout codebase
        - name: Checkout snuba
          uses: actions/checkout@v2

        # Checkout Sentry and run integration tests against latest snuba
        - name: Checkout sentry
          uses: actions/checkout@v2
          with:
            repository: getsentry/sentry
            path: sentry

        - name: Get branch name (merge)
          id: branch
          run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | tr / -)"

        # setup python
        - uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Setup steps
          id: setup
          run: |
            pip install --upgrade pip wheel
            echo "::set-output name=pip-cache-dir::$(pip cache dir)"
            # We cannot execute actions that are not placed under .github of the main repo
            mkdir -p .github/actions/setup-sentry/
            cp sentry/.github/actions/setup-sentry/action.yml .github/actions/setup-sentry/action.yml

        - name: Sentry's pip cache
          uses: actions/cache@v2
          with:
            path: ${{ steps.setup.outputs.pip-cache-dir }}
            key: sentry-deps-${{ hashFiles('sentry/requirements**.txt') }}
            restore-keys: sentry-deps-

        - name: Setup Sentry
          id: setup-sentry
          uses: ./.github/actions/setup-sentry
          with:
            working-dir: sentry
            snuba: false
            kafka: true

        - run: sentry devservices up clickhouse

        - name: Build snuba docker image
          run: |
            docker pull getsentry/snuba:latest || true
            docker build . \
              --build-arg PYTHON_VERSION=3.8 \
              -t getsentry/snuba \
              --cache-from getsentry/snuba:latest \
              --target testing

        - name: Start snuba
          run: |
            docker run -d --rm \
              -p 127.0.0.1:1218:1218 \
              -e PYTHONUNBUFFERED=1 \
              -e SNUBA_SETTINGS=docker \
              -e DEBUG=1 \
              -e DEFAULT_BROKERS=sentry_kafka:9092 \
              -e CLICKHOUSE_HOST=sentry_clickhouse \
              -e CLICKHOUSE_PORT=9000 \
              -e CLICKHOUSE_HTTP_PORT=8123 \
              -e REDIS_HOST=sentry_redis \
              -e REDIS_PORT=6379 \
              -e REDIS_DB=1 \
              --name sentry_snuba \
              --network sentry \
              getsentry/snuba:latest
            docker exec sentry_snuba snuba migrations migrate --force

        - name: Run tests
          run: |
            cd sentry && make test-snuba

    acceptance:
      # if: false == true
      runs-on: ubuntu-16.04
      # continue-on-error: true
      strategy:
        matrix:
          instance: [0, 1]

      steps:
        # Checkout codebase
        - name: Checkout snuba
          uses: actions/checkout@v2

        # Checkout Sentry and run integration tests against latest snuba
        - name: Checkout sentry
          uses: actions/checkout@v2
          with:
            repository: getsentry/sentry
            path: sentry
            # ref: test/snuba/testing-snuba-integration

        - name: Copy frontend assets from sentry image
          run: |
            ls sentry/src/sentry/static/sentry
            mkdir -p sentry/src/sentry/static/sentry/dist
            id=$(docker run -it -d getsentry/sentry:latest bash)
            docker cp ${id}:/usr/local/lib/python3.6/site-packages/sentry/static/sentry/dist sentry/src/sentry/static/sentry/dist

        # setup python
        - uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Setup steps
          id: setup
          run: |
            pip install --upgrade pip wheel
            echo "::set-output name=pip-cache-dir::$(pip cache dir)"
            # We cannot execute actions that are not placed under .github of the main repo
            mkdir -p .github/actions/setup-sentry/
            cp sentry/.github/actions/setup-sentry/action.yml .github/actions/setup-sentry/action.yml

        - name: Sentry's pip cache
          uses: actions/cache@v2
          with:
            path: ${{ steps.setup.outputs.pip-cache-dir }}
            key: sentry-deps-${{ hashFiles('sentry/requirements**.txt') }}
            restore-keys: sentry-deps-

        - name: Setup Sentry
          uses: ./.github/actions/setup-sentry
          id: setup-sentry
          with:
            working-dir: sentry
            snuba: false
            kafka: true

        - run: sentry devservices up clickhouse

        - name: Build snuba docker image
          run: |
            docker pull getsentry/snuba:latest || true
            docker build . \
              --build-arg PYTHON_VERSION=3.8 \
              -t getsentry/snuba \
              --cache-from getsentry/snuba:latest \
              --target testing

        - name: Start snuba
          run: |
            docker run -d --rm \
              -p 127.0.0.1:1218:1218 \
              -e PYTHONUNBUFFERED=1 \
              -e SNUBA_SETTINGS=docker \
              -e DEBUG=1 \
              -e CLICKHOUSE_HOST=sentry_clickhouse \
              -e CLICKHOUSE_PORT=9000 \
              -e CLICKHOUSE_HTTP_PORT=8123 \
              -e REDIS_HOST=sentry_redis \
              -e REDIS_PORT=6379 \
              -e REDIS_DB=1 \
              --name sentry_snuba \
              --network sentry \
              getsentry/snuba:latest
            docker exec sentry_snuba snuba migrations migrate --force

        # - uses: volta-cli/action@v1

        # - name: Install Javascript Dependencies
          # run: |
            # cd sentry && yarn install --frozen-lockfile

        # - name: webpack
          # run: |
            # cd sentry && yarn build-acceptance

        - name: Run acceptance tests (#${{ steps.setup-sentry.outputs.matrix-instance-number }} of ${{ strategy.job-total }})
          env:
            RUN_SNUBA_TESTS_ONLY: 1
            USE_SNUBA: 1
          run: |
            cd sentry && make run-acceptance
